version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

  web:
    build: .
    command: 'uvicorn api:app --host=0.0.0.0 --reload'
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - $PWD:/app
