version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  web:
    build: .
    depends_on:
      - mongo
    volumes:
      - $PWD:/app
