name: Run a specific scraper

on:
  workflow_call:
    inputs:
      scraper:
        required: true
        type: string

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run worker
        uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          timeout_minutes: 3
          max_attempts: 10
          retry_on: error
          command: |
            python -m scraper.${{ inputs.scraper }}
