name: Run a specific scraper

on:
  workflow_call:
    inputs:
      scraper:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  run_scraper:
    runs-on: ${{ inputs.image_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run worker
        uses: nick-fields/retry@v3
        env:
          DATA_FETCHED_WEBHOOK: ${{ secrets.DATA_FETCHED_WEBHOOK }}
          DB_NAME: ${{ secrets.DB_NAME }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          timeout_minutes: 3
          max_attempts: 3
          retry_on: error
          command: |
            python3 -m scraper.${{ inputs.scraper }}
