on:
  workflow_dispatch:
  schedule:
    - cron: '13 */6 * * *'

name: worker

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  LATEST_TAG: latest

jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Downcase image name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME@L}" >>${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        name: Setup buildx
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.LATEST_TAG }}

  collect_data:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Downcase image name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME@L}" >>${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run worker
        uses: nick-fields/retry@v3
        env:
          DATA_FETCHED_WEBHOOK: ${{ secrets.DATA_FETCHED_WEBHOOK }}
          DB_NAME: ${{ secrets.DB_NAME }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          timeout_minutes: 3
          max_attempts: 3
          retry_on: error
          command: |
            docker run -e DATA_FETCHED_WEBHOOK -e DB_NAME -e MONGODB_URI \
              -v /dev/shm:/dev/shm \
              --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.LATEST_TAG }} python3 -m scraper
