on:
  workflow_dispatch:
  schedule:
    - cron: '13 */6 * * *'

name: worker

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: flexicon/tft-suggester/worker

jobs:
  scrape_champions:
    uses: ./.github/workflows/run_scraper.yml
    secrets: inherit
    with:
      scraper: scrape_champions

  scrape_comps:
    uses: ./.github/workflows/run_scraper.yml
    secrets: inherit
    with:
      scraper: scrape_comps

  scrape_items:
    uses: ./.github/workflows/run_scraper.yml
    secrets: inherit
    with:
      scraper: scrape_items

  trigger_webhook:
    runs-on: ubuntu-latest
    needs:
      - scrape_champions
      - scrape_comps
      - scrape_items
    steps:
      - name: curl
        run: |
          curl -X POST ${{ secrets.DATA_FETCHED_WEBHOOK }}
